/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service root and endpoint index */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus exposition */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account (email + bcrypt-hashed password).
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and issue a signed access token.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Books
         * @description List the books the current user owns (the shelf), newest first.
         */
        get: operations["list_books_api_books_get"];
        put?: never;
        /**
         * Upload Book
         * @description Validate + store a PDF/EPUB, create the book, and trigger Phase A ingest.
         *
         *     Returns the freshly-created book (status ``importing``) directly — the shelf
         *     prepends it and polls until it is ``ready``.
         *
         *     Defends the ingest pipeline: the content-type is checked, the per-user book
         *     quota is enforced, the body is read **streaming** (aborting the moment it
         *     crosses ``MAX_PDF_BYTES`` rather than buffering an oversized payload), the
         *     format is detected by content magic, an EPUB is normalised to PDF, and the
         *     page count is capped (``MAX_INGEST_PAGES``) before any token-spending ingest
         *     is triggered.
         */
        post: operations["upload_book_api_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book
         * @description Fetch a book with its import status + progress.
         */
        get: operations["get_book_api_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/{page_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page
         * @description A page's presigned image URL, text, and per-word boxes (§9.4).
         */
        get: operations["get_page_api_books__book_id__pages__page_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/canon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Canon
         * @description The book's canon graph: the entity list the Director editor renders, plus
         *     the human-inspectable markdown vault export (§8.1).
         */
        get: operations["get_canon_api_books__book_id__canon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Shots
         * @description The book's shots (the §5.4 shot timeline) as a bare array.
         */
        get: operations["list_shots_api_books__book_id__shots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Open a reading session against a book (Redis control state + a durable row).
         */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Return the Scheduler's live control state for a session.
         */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Intent
         * @description Apply a debounced reading-intent update and run one control tick (§4.9).
         */
        post: operations["update_intent_api_sessions__session_id__intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seek
         * @description Jump to a word: cancel distant work, bridge keyframe, re-seed (§4.8).
         */
        post: operations["seek_api_sessions__session_id__seek_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Comment
         * @description Classify a Director region-comment, enqueue a regen, emit agent_activity (§5.4).
         */
        post: operations["comment_api_sessions__session_id__comment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/canon_edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Canon Edit
         * @description Edit a canon entity and surgically regen only the dependent shots (§8.7).
         */
        post: operations["canon_edit_api_books__book_id__canon_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/conflict_choice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conflict Choice
         * @description Apply the Director's resolution of a surfaced conflict (§7.2).
         *
         *     Records the pick, streams the Showrunner's arbitration reasoning into the feed,
         *     and **acts on it**: ``honor_canon`` regenerates the shot honouring the canon,
         *     ``evolve_canon`` writes the new state then regenerates, ``surface_to_user``
         *     leaves it surfaced. The affected shot's fresh clip closes the loop (a
         *     ``regen_done`` event), so the §16 demo resolves a conflict live.
         */
        post: operations["conflict_choice_api_sessions__session_id__conflict_choice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Directing Style
         * @description The reader's accumulated directing style across all their books (§8.6).
         */
        get: operations["my_directing_style_api_me_prefs_get"];
        put?: never;
        post?: never;
        /**
         * Reset My Directing Style
         * @description Clear the reader's learned directing style everywhere (global reset, §8.6).
         */
        delete: operations["reset_my_directing_style_api_me_prefs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Book Directing Style
         * @description The directing style learned for one book — what its shots default to (§8.6).
         */
        get: operations["book_directing_style_api_books__book_id__prefs_get"];
        put?: never;
        post?: never;
        /**
         * Reset Book Directing Style
         * @description Clear the directing style learned for one book (§8.6).
         */
        delete: operations["reset_book_directing_style_api_books__book_id__prefs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Events
         * @description SSE stream of this session's §5.6 generation events.
         */
        get: operations["session_events_api_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Library Events
         * @description SSE stream of ingest progress for the signed-in user's library (§5.1).
         *
         *     The shelf subscribes here for live ``ingest_progress`` events instead of
         *     polling alone. Events are published on the per-user library channel while
         *     Phase A runs.
         */
        get: operations["library_events_api_books_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/buffer-trace/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Buffer Trace
         * @description Recompute the §4.10 watermark sawtooth for a session (zero video-seconds).
         *
         *     Ownership is enforced against the durable session row; the live Scheduler
         *     control state (Redis) supplies the current focus word + velocity when present,
         *     otherwise the durable row's values are used.
         */
        get: operations["get_buffer_trace_api_eval_buffer_trace__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/report/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Return the cached crew-vs-baseline §13 report for a book (exact contract).
         *
         *     The report is produced (and cached) by ``python -m app.eval.run --book
         *     <book_id>``; running both arms on demand inside the request path is
         *     deliberately avoided (it is expensive). A 404 with guidance is returned when
         *     no report has been cached yet.
         */
        get: operations["get_report_api_eval_report__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_book_api_books_post */
        Body_upload_book_api_books_post: {
            /**
             * File
             * @description The source PDF or EPUB
             */
            file: string;
            /** Title */
            title?: string | null;
            /** Author */
            author?: string | null;
            /** Art Direction */
            art_direction?: string | null;
        };
        /**
         * BookResponse
         * @description A book on the shelf, with its import status and progress (§5.1).
         *
         *     The collection endpoints (``GET /books``) return a *bare* ``list`` of these,
         *     and the upload endpoint returns a bare ``BookResponse`` — the frontend client
         *     parses ``Book[]`` / ``Book`` directly (no envelope).
         */
        BookResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Status */
            status: string;
            /** Num Pages */
            num_pages?: number | null;
            /** Art Direction */
            art_direction?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Progress */
            progress?: number | null;
            /** Stage */
            stage?: string | null;
        };
        /**
         * BufferTracePoint
         * @description One sample on the committed-buffer sawtooth (the shared contract item).
         */
        BufferTracePoint: {
            /** T */
            t: number;
            /** Committed Seconds Ahead */
            committed_seconds_ahead: number;
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /**
         * CanonAppearance
         * @description An entity's appearance block with presigned reference-image URLs.
         */
        CanonAppearance: {
            /** Description */
            description?: string | null;
            /** Reference Images */
            reference_images?: components["schemas"]["CanonReferenceImage"][];
        };
        /**
         * CanonEditRequest
         * @description An edit to a canon entity, triggering surgical dependent regen (§5.4/§8.7).
         */
        CanonEditRequest: {
            /** Entity Key */
            entity_key: string;
            /** Changes */
            changes?: {
                [key: string]: unknown;
            };
            /** Valid From Beat */
            valid_from_beat?: number | null;
        };
        /**
         * CanonEditResponse
         * @description The new entity version + the dependent shots queued for regen (§8.7).
         *
         *     ``affected_shot_ids`` are the dependent shots the edit re-rendered — the name
         *     the frontend's canon editor reads to mark those shots "rendering".
         */
        CanonEditResponse: {
            /** Entity Key */
            entity_key: string;
            /** Version */
            version: number;
            /** Affected Shot Ids */
            affected_shot_ids?: string[];
            /**
             * Skipped Shots
             * @default 0
             */
            skipped_shots: number;
        };
        /**
         * CanonEntityResponse
         * @description One canon entity (current version) projected for the §5.4 canon editor.
         *
         *     ``id`` is the stable ``entity_key`` (what the canon-edit call targets), not
         *     the per-version DB row id.
         */
        CanonEntityResponse: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Description */
            description?: string | null;
            appearance?: components["schemas"]["CanonAppearance"] | null;
            /** Style Tokens */
            style_tokens?: {
                [key: string]: unknown;
            } | null;
            /** Voice */
            voice?: {
                [key: string]: unknown;
            } | null;
            /** Version */
            version: number;
            /** Valid From Beat */
            valid_from_beat?: number | null;
            /** Valid To Beat */
            valid_to_beat?: number | null;
            /** First Appearance */
            first_appearance?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CanonReferenceImage
         * @description A locked reference image projected for the Director's canon editor.
         *
         *     ``oss_url`` is an ephemeral presigned GET URL (for display); ``oss_key`` is the
         *     durable object-store key. The editor echoes ``oss_key`` back inside a
         *     ``canon_edit`` ``changes.appearance`` so a locked-reference swap round-trips
         *     losslessly — the presigned URL can't be re-stored, the key can (§5.4/§8.1).
         */
        CanonReferenceImage: {
            /** Oss Url */
            oss_url: string;
            /** Oss Key */
            oss_key?: string | null;
            /** Pose */
            pose?: string | null;
            /** Locked */
            locked?: boolean | null;
        };
        /**
         * CanonResponse
         * @description The canon graph for a book: the entity list the Director editor renders,
         *     the versioned continuity facts (§8.5), plus the optional human-inspectable
         *     markdown vault export (§8.1).
         */
        CanonResponse: {
            /** Book Id */
            book_id: string;
            /** Entities */
            entities?: components["schemas"]["CanonEntityResponse"][];
            /** States */
            states?: components["schemas"]["CanonStateResponse"][];
            /** Markdown */
            markdown?: string | null;
        };
        /**
         * CanonStateResponse
         * @description A versioned continuity fact projected for the canon editor (§8.5).
         *
         *     A ``(subject, predicate, object)`` triple true only over a beat interval;
         *     ``valid_to_beat is None`` means still active, a value means it was *retired*
         *     (the "forgetting" mechanism) — the editor shows both so the timeline of what
         *     the story currently believes (and used to) is inspectable.
         */
        CanonStateResponse: {
            /** Id */
            id: string;
            /** Subject Entity Key */
            subject_entity_key: string;
            /** Predicate */
            predicate: string;
            /** Object Value */
            object_value: string;
            /** Valid From Beat */
            valid_from_beat: number;
            /** Valid To Beat */
            valid_to_beat?: number | null;
            /** Version */
            version: number;
            /** Active */
            active: boolean;
            /** Source Span */
            source_span?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CommentRequest
         * @description A Director region-comment: a screenshot + a natural-language note (§5.4).
         */
        CommentRequest: {
            /** Shot Id */
            shot_id: string;
            /** Note */
            note: string;
            /** Region Png */
            region_png?: string | null;
        };
        /**
         * CommentResponse
         * @description How a comment was routed and the regen it triggered (§5.4).
         *
         *     ``learned`` is the directing priors this note taught (§8.6) — usually empty,
         *     but non-empty when the note nudged a pacing/palette/framing default, so the
         *     client can confirm "Noted — slower shots will be the default" at teach time.
         */
        CommentResponse: {
            /** Shot Id */
            shot_id: string;
            /** Agent */
            agent: string;
            /** Aspect */
            aspect: string;
            /** Message */
            message: string;
            /** Job Id */
            job_id?: string | null;
            /** Learned */
            learned?: components["schemas"]["DirectingPriorView"][];
        };
        /**
         * ConflictChoiceRequest
         * @description The Director's resolution of a surfaced conflict (§7.2).
         */
        ConflictChoiceRequest: {
            /** Conflict Id */
            conflict_id: string;
            option: components["schemas"]["ConflictOption"];
        };
        /**
         * ConflictChoiceResponse
         * @description Acknowledgement of a conflict resolution (§7.2).
         */
        ConflictChoiceResponse: {
            /** Conflict Id */
            conflict_id: string;
            option: components["schemas"]["ConflictOption"];
            /**
             * Status
             * @default recorded
             */
            status: string;
            /** Shot Id */
            shot_id?: string | null;
            /** Reasoning */
            reasoning?: string | null;
        };
        /**
         * ConflictOption
         * @description The fixed set of resolutions the Showrunner policy arbitrates between.
         * @enum {string}
         */
        ConflictOption: "honor_canon" | "surface_to_user" | "evolve_canon";
        /**
         * CreateSessionRequest
         * @description Open a reading session against a book.
         */
        CreateSessionRequest: {
            /** Book Id */
            book_id: string;
            /**
             * Focus Word
             * @default 0
             */
            focus_word: number;
            /**
             * Mode
             * @default viewer
             */
            mode: string;
        };
        /**
         * DirectingPriorView
         * @description One learned directing prior, projected as plain language for the panel.
         *
         *     ``bias`` is the signed strength (negative = slower/cooler/closer, positive =
         *     faster/warmer/wider); ``applied`` is whether it is strong enough to default a
         *     future shot; ``applied_value`` is the concrete default it sets (``slow`` /
         *     ``wide`` / …) when applied.
         */
        DirectingPriorView: {
            /** Kind */
            kind: string;
            /** Bias */
            bias: number;
            /** Weight */
            weight: number;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Applied */
            applied: boolean;
            /** Applied Value */
            applied_value?: string | null;
        };
        /**
         * DirectingStyleResponse
         * @description The reader's accumulated directing style for a scope (§8.6).
         *
         *     ``scope`` is ``"book"`` (this title) or ``"user"`` (all books). Empty
         *     ``priors`` means nothing has been learned yet — the panel shows its zero-state.
         */
        DirectingStyleResponse: {
            /** Scope */
            scope: string;
            /** Book Id */
            book_id?: string | null;
            /** Priors */
            priors?: components["schemas"]["DirectingPriorView"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntentRequest
         * @description A debounced reading-intent update (§4.3): focus word ``w`` + velocity ``v``.
         */
        IntentRequest: {
            /** Focus Word */
            focus_word: number;
            /**
             * Velocity
             * @default 4
             */
            velocity: number;
            /** Mode */
            mode?: string | null;
        };
        /**
         * IntentResponse
         * @description What one control tick did (§4.9): promotions, keyframes, buffer state.
         */
        IntentResponse: {
            /** Session Id */
            session_id: string;
            /** Settled */
            settled: boolean;
            /**
             * Allow Promotion
             * @default false
             */
            allow_promotion: boolean;
            /**
             * Idle
             * @default false
             */
            idle: boolean;
            /**
             * Bursting
             * @default false
             */
            bursting: boolean;
            /**
             * Committed Seconds Ahead
             * @default 0
             */
            committed_seconds_ahead: number;
            /** Promoted */
            promoted?: string[];
            /** Keyframed */
            keyframed?: string[];
            /**
             * Cancelled
             * @default 0
             */
            cancelled: number;
        };
        /**
         * LoginRequest
         * @description Exchange credentials for an access token.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PageResponse
         * @description One rendered page: a presigned image URL, text, and per-word boxes (§9.4).
         */
        PageResponse: {
            /** Book Id */
            book_id: string;
            /** Page Number */
            page_number: number;
            /** Image Url */
            image_url?: string | null;
            /** Text */
            text?: string | null;
            /** Word Boxes */
            word_boxes?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * RegisterRequest
         * @description Create an account.
         */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ResetPrefsResponse
         * @description Acknowledgement that learned priors were cleared (§8.6).
         */
        ResetPrefsResponse: {
            /** Scope */
            scope: string;
            /** Book Id */
            book_id?: string | null;
            /**
             * Cleared
             * @default 0
             */
            cleared: number;
        };
        /**
         * SeekRequest
         * @description A jump to a word (§4.8): cancel distant work, bridge, re-seed.
         */
        SeekRequest: {
            /** Word */
            word: number;
        };
        /**
         * SeekResponse
         * @description The outcome of a seek (§4.8).
         */
        SeekResponse: {
            /** Session Id */
            session_id: string;
            /** Word */
            word: number;
            /** Cancelled */
            cancelled: number;
            /** Bridge Beat */
            bridge_beat?: string | null;
            /**
             * Committed Seconds Ahead
             * @default 0
             */
            committed_seconds_ahead: number;
        };
        /**
         * SessionResponse
         * @description The Scheduler's view of a reading session (§4.9).
         */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            /** Book Id */
            book_id: string;
            /** Focus Word */
            focus_word: number;
            /** Velocity Wps */
            velocity_wps: number;
            /** Mode */
            mode: string;
            /** Committed Seconds Ahead */
            committed_seconds_ahead: number;
            /**
             * Bursting
             * @default false
             */
            bursting: boolean;
            /** Budget Remaining S */
            budget_remaining_s?: number | null;
            /** Inflight */
            inflight?: {
                [key: string]: string[];
            };
        };
        /**
         * ShotResponse
         * @description A shot's episodic record projected for the timeline / Director tools.
         *
         *     Includes ``source_span`` so the client's SyncEngine can sort/seek by reading
         *     position; the §5.4 timeline returns a *bare* ``list`` of these.
         */
        ShotResponse: {
            /** Shot Id */
            shot_id: string;
            /** Beat Id */
            beat_id?: string | null;
            /** Scene Id */
            scene_id?: string | null;
            /** Source Span */
            source_span?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Render Mode */
            render_mode?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Qa */
            qa?: {
                [key: string]: unknown;
            } | null;
            /** Clip Url */
            clip_url?: string | null;
            /** Reference Image Ids */
            reference_image_ids?: string[];
        };
        /**
         * TokenResponse
         * @description A freshly-issued access token.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * UserResponse
         * @description A public view of a user account.
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Created At */
            created_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_books_api_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"][];
                };
            };
        };
    };
    upload_book_api_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_book_api_books_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_books__book_id__pages__page_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                page_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_canon_api_books__book_id__canon_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shots_api_books__book_id__shots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_intent_api_sessions__session_id__intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seek_api_sessions__session_id__seek_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeekResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comment_api_sessions__session_id__comment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    canon_edit_api_books__book_id__canon_edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanonEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonEditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conflict_choice_api_sessions__session_id__conflict_choice_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConflictChoiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictChoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_directing_style_api_me_prefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectingStyleResponse"];
                };
            };
        };
    };
    reset_my_directing_style_api_me_prefs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPrefsResponse"];
                };
            };
        };
    };
    book_directing_style_api_books__book_id__prefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectingStyleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_book_directing_style_api_books__book_id__prefs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPrefsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_events_api_sessions__session_id__events_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_events_api_books_events_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_buffer_trace_api_eval_buffer_trace__session_id__get: {
        parameters: {
            query?: {
                velocity?: number | null;
                duration_s?: number | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BufferTracePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_eval_report__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
