"""Phase 2 data layer: postgres+pgvector schema

Revision ID: 0426a4023e7c
Revises: 
Create Date: 2026-06-22 17:27:03.032918

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0426a4023e7c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The pgvector extension must exist before any table with a ``vector`` column
    # (entities.embedding, shots.embedding) is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('source_pdf_key', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('importing', 'ready', 'failed', name='book_status', native_enum=False), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('art_direction', sa.Text(), nullable=True),
    sa.Column('watermark_low_s', sa.Float(), nullable=True),
    sa.Column('watermark_high_s', sa.Float(), nullable=True),
    sa.Column('commit_horizon_s', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_index(op.f('ix_books_status'), 'books', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('continuity_states',
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('subject_entity_key', sa.String(length=128), nullable=False),
    sa.Column('predicate', sa.String(length=256), nullable=False),
    sa.Column('object_value', sa.Text(), nullable=False),
    sa.Column('valid_from_beat', sa.Integer(), nullable=False),
    sa.Column('valid_to_beat', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_span', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_continuity_states_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuity_states'))
    )
    op.create_index('ix_continuity_states_book_from', 'continuity_states', ['book_id', 'valid_from_beat'], unique=False)
    op.create_index(op.f('ix_continuity_states_book_id'), 'continuity_states', ['book_id'], unique=False)
    op.create_index('ix_continuity_states_subject', 'continuity_states', ['book_id', 'subject_entity_key'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('character', 'location', 'prop', 'style', name='entity_type', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voice', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', Vector(1152), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valid_from_beat', sa.Integer(), nullable=False),
    sa.Column('valid_to_beat', sa.Integer(), nullable=True),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.Column('first_appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_entities_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes'], ['entities.id'], name=op.f('fk_entities_supersedes_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('book_id', 'entity_key', 'version', name=op.f('uq_entities_book_id_entity_key_version'))
    )
    op.create_index(op.f('ix_entities_book_id'), 'entities', ['book_id'], unique=False)
    op.create_index('ix_entities_book_key', 'entities', ['book_id', 'entity_key'], unique=False)
    op.create_index('ix_entities_book_type', 'entities', ['book_id', 'type'], unique=False)
    op.create_table('pages',
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=1024), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('word_boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_pages_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('book_id', 'page_number', name=op.f('uq_pages_book_id_page_number'))
    )
    op.create_index(op.f('ix_pages_book_id'), 'pages', ['book_id'], unique=False)
    op.create_table('prefs',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('book_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_prefs_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prefs'))
    )
    op.create_index(op.f('ix_prefs_book_id'), 'prefs', ['book_id'], unique=False)
    op.create_index('ix_prefs_scope_kind', 'prefs', ['user_id', 'book_id', 'kind'], unique=False)
    op.create_index(op.f('ix_prefs_user_id'), 'prefs', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('focus_word', sa.Integer(), nullable=False),
    sa.Column('velocity_wps', sa.Float(), nullable=False),
    sa.Column('committed_seconds_ahead', sa.Float(), nullable=False),
    sa.Column('mode', sa.Enum('viewer', 'director', name='session_mode', native_enum=False), nullable=False),
    sa.Column('inflight', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_remaining_s', sa.Float(), nullable=True),
    sa.Column('last_activity_ms', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_sessions_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_book_id'), 'sessions', ['book_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('shot_cache',
    sa.Column('shot_hash', sa.String(length=128), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('clip_key', sa.String(length=1024), nullable=True),
    sa.Column('last_frame_key', sa.String(length=1024), nullable=True),
    sa.Column('sync_segment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qa', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_shot_cache_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shot_hash', name=op.f('pk_shot_cache'))
    )
    op.create_index(op.f('ix_shot_cache_book_id'), 'shot_cache', ['book_id'], unique=False)
    op.create_table('shots',
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=True),
    sa.Column('beat_id', sa.String(length=64), nullable=True),
    sa.Column('source_span', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('planned', 'keyframed', 'promoted', 'rendering', 'qa', 'accepted', 'degraded', 'conflict', name='shot_status', native_enum=False), nullable=False),
    sa.Column('render_mode', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('reference_set_hash', sa.String(length=128), nullable=True),
    sa.Column('reference_image_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qa', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', Vector(1152), nullable=True),
    sa.Column('canon_version_at_render', sa.Integer(), nullable=True),
    sa.Column('shot_hash', sa.String(length=128), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_shots_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )
    op.create_index('ix_shots_book_beat', 'shots', ['book_id', 'beat_id'], unique=False)
    op.create_index(op.f('ix_shots_book_id'), 'shots', ['book_id'], unique=False)
    op.create_index('ix_shots_book_status', 'shots', ['book_id', 'status'], unique=False)
    op.create_index(op.f('ix_shots_scene_id'), 'shots', ['scene_id'], unique=False)
    op.create_index(op.f('ix_shots_shot_hash'), 'shots', ['shot_hash'], unique=True)
    op.create_index(op.f('ix_shots_status'), 'shots', ['status'], unique=False)
    op.create_table('defects',
    sa.Column('shot_id', sa.String(length=64), nullable=True),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_defects_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_defects_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defects'))
    )
    op.create_index(op.f('ix_defects_book_id'), 'defects', ['book_id'], unique=False)
    op.create_index(op.f('ix_defects_shot_id'), 'defects', ['shot_id'], unique=False)
    op.create_table('render_jobs',
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('shot_id', sa.String(length=64), nullable=True),
    sa.Column('shot_hash', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Enum('committed', 'speculative', 'keyframe', name='render_priority', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'reserved', 'submitted', 'polling', 'succeeded', 'retrying', 'cancelled', 'deadletter', name='render_job_status', native_enum=False), nullable=False),
    sa.Column('cancel_token', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('provider_task_id', sa.String(length=256), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('reserved_video_s', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_render_jobs_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_render_jobs_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_jobs'))
    )
    op.create_index(op.f('ix_render_jobs_session_id'), 'render_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_render_jobs_shot_hash'), 'render_jobs', ['shot_hash'], unique=False)
    op.create_index(op.f('ix_render_jobs_shot_id'), 'render_jobs', ['shot_id'], unique=False)
    op.create_index(op.f('ix_render_jobs_status'), 'render_jobs', ['status'], unique=False)
    op.create_table('source_span_index',
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('word_index_start', sa.Integer(), nullable=False),
    sa.Column('word_index_end', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=True),
    sa.Column('beat_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_source_span_index_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_source_span_index_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_span_index'))
    )
    op.create_index('ix_source_span_index_book_word', 'source_span_index', ['book_id', 'word_index_start'], unique=False)
    op.create_index(op.f('ix_source_span_index_shot_id'), 'source_span_index', ['shot_id'], unique=False)
    # ### end Alembic commands ###

    # pgvector HNSW approximate-nearest-neighbour indexes for cosine distance
    # (``<=>``). Autogenerate cannot emit these; they back episodic.search
    # (kinora.md §8.2). HNSW gives better recall than ivfflat and needs no
    # training data, so it is ideal for a database that grows incrementally; the
    # 1152-d embeddings are within HNSW's 2000-dim cosine limit.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_entities_embedding ON entities "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_shots_embedding ON shots "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    # Drop the pgvector ANN indexes first (the ``vector`` extension itself is
    # intentionally left in place — dropping it is destructive and other objects
    # may depend on it).
    op.execute("DROP INDEX IF EXISTS ix_shots_embedding")
    op.execute("DROP INDEX IF EXISTS ix_entities_embedding")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_span_index_shot_id'), table_name='source_span_index')
    op.drop_index('ix_source_span_index_book_word', table_name='source_span_index')
    op.drop_table('source_span_index')
    op.drop_index(op.f('ix_render_jobs_status'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_shot_id'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_shot_hash'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_session_id'), table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index(op.f('ix_defects_shot_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_book_id'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_shots_status'), table_name='shots')
    op.drop_index(op.f('ix_shots_shot_hash'), table_name='shots')
    op.drop_index(op.f('ix_shots_scene_id'), table_name='shots')
    op.drop_index('ix_shots_book_status', table_name='shots')
    op.drop_index(op.f('ix_shots_book_id'), table_name='shots')
    op.drop_index('ix_shots_book_beat', table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_shot_cache_book_id'), table_name='shot_cache')
    op.drop_table('shot_cache')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_book_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_prefs_user_id'), table_name='prefs')
    op.drop_index('ix_prefs_scope_kind', table_name='prefs')
    op.drop_index(op.f('ix_prefs_book_id'), table_name='prefs')
    op.drop_table('prefs')
    op.drop_index(op.f('ix_pages_book_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_entities_book_type', table_name='entities')
    op.drop_index('ix_entities_book_key', table_name='entities')
    op.drop_index(op.f('ix_entities_book_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_continuity_states_subject', table_name='continuity_states')
    op.drop_index(op.f('ix_continuity_states_book_id'), table_name='continuity_states')
    op.drop_index('ix_continuity_states_book_from', table_name='continuity_states')
    op.drop_table('continuity_states')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_status'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
